version: 2
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: fukamachi/sbcl:2.2.2-debian
        environment:
          APP_ENV: test
    steps:
      - checkout
      - run: apt update -y && apt install -y curl gpg
      - run: chmod a+x ./.circleci/*.sh
      - run:
          name: Install Quicklisp
          command: .circleci/install_quicklisp.sh
      - run:
          name: Install Roswell Lisp Manager
          pre:
            - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
            - case $CIRCLE_NODE_INDEX in
 	            0) ros config set default.lisp sbcl-bin ;;
 	            1) ros install ccl-bin;
  		          ros config set default.lisp ccl-bin ;;
      	      esac
            - ros run -- --version
      - run:
          name: Display SBCL information
          command: .circleci/sbcl_info.sh
      - run:
          name: Install project dependencies
          command: .circleci/install_deps.sh
      # - run:
      #     name: Run CS tests
      #     command: .circleci/php_lint.sh
      - run:
          name: Run SBCL Unit tests
          command: .circleci/sbcl_unit_tests.sh
